fix: unpin selenium test dependency
This change unpins selenium and selenium-wire dependencies to fix failing tests.  Prior to this change, integration tests failed on the command  Prior to this change, test_charms.py line `from seleniumwire import webdriver` failed with the error `AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'`, probably due to an incompatible package (maybe one of their dependencies was unpinned?).  Unpinning selenium/selenium-wire fixes these issues.